"""
SentinelScope Report Module
Generates Markdown for UI display and branded PDF for insurance/legal export.
"""

import io
from datetime import datetime

import pandas as pd
from fpdf2 import FPDF


# --- 1. PDF CLASS FOR BRANDING ---
class SentinelAuditPDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 16)
        self.set_text_color(30, 58, 138)  # Professional Navy Blue
        self.cell(0, 12, "SENTINELSCOPE: NYC COMPLIANCE AUDIT", ln=1)
        self.set_draw_color(30, 58, 138)
        self.line(10, 28, 200, 28)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(
            0, 10, f"Page {self.page_no()} | Generated by SentinelScope AI", align="C"
        )


# --- 2. THE REPORT ENGINE ---
def generate_report_content(classified_data: pd.DataFrame, gap_analysis: dict):
    """
    Orchestrates report creation.
    Returns: (markdown_text, pdf_bytes)
    """
    # Create Table Rows for MD and PDF
    table_rows = []
    for _, row in classified_data.iterrows():
        milestone = row.get("milestone", "")
        has_gap = any(
            missing.lower() in milestone.lower()
            for missing in gap_analysis.get("missing_milestones", [])
        )

        table_rows.append(
            {
                "Date": row.get("date", ""),
                "Location": row.get("location", "Unknown"),
                "Milestone": milestone,
                "Gap": "ALERT" if has_gap else "OK",
                "Confidence": f"{row.get('confidence', 0)*100:.0f}%",
            }
        )

    df_table = pd.DataFrame(table_rows)

    # --- Generate Markdown (For UI) ---
    md_report = f"""# Construction Evidence Report
**Date:** {datetime.now().strftime('%Y-%m-%d')}
**Project Status:** {gap_analysis.get('risk_level', 'Unknown')}

## 📊 Summary
- **Coverage**: {gap_analysis.get('coverage_percentage', 0)}%
- **Gaps Found**: {gap_analysis.get('gap_count', 0)}

## 🧾 Evidence Table
{df_table.to_markdown(index=False)}
"""

    # --- Generate PDF (For Export) ---
    pdf = SentinelAuditPDF()
    pdf.add_page()

    # Executive Summary
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "EXECUTIVE SUMMARY", ln=1)
    pdf.set_font("helvetica", "", 11)
    pdf.multi_cell(
        0,
        8,
        f"Project Risk: {gap_analysis.get('risk_level')}\n"
        f"Coverage: {gap_analysis.get('coverage_percentage')}%\n"
        f"Recommendations: {gap_analysis.get('recommendation')}",
    )
    pdf.ln(5)

    # Simple Table for PDF
    pdf.set_font("helvetica", "B", 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(30, 10, "Date", 1, 0, "C", True)
    pdf.cell(50, 10, "Location", 1, 0, "C", True)
    pdf.cell(70, 10, "Milestone", 1, 0, "C", True)
    pdf.cell(30, 10, "Status", 1, 1, "C", True)

    pdf.set_font("helvetica", "", 9)
    for _, row in df_table.iterrows():
        pdf.cell(30, 10, str(row["Date"]), 1)
        pdf.cell(50, 10, str(row["Location"]), 1)
        pdf.cell(70, 10, str(row["Milestone"]), 1)
        pdf.cell(30, 10, str(row["Gap"]), 1, 1)

    return md_report, pdf.output()
